# encoding: UTF-8

module LoremText
  #Text taken from http://en.wikipedia.org/wiki/Template:Lorem_ipsum
  FULL = %q{Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  This continues at length and variously. The text is not really Greek, but badly garbled Latin. It started life as extracted phrases from sections 1.10.32 and 1.10.33 of Cicero's De Finibus Bonorum et Malorum Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?  At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. }
  LA = FULL
  ES = %q{Lorem ipsum dolor sit amet, consectetaur enfoque mental, pueden ayudarle a ahorrar tiempo, dinero y Hawaii. Para tomar un ejemplo trivial, queremos saber de usted. No hay productos en esta categoría serán enviados a este artículo. No hay productos, que va a composición tipográfica electrónica, quedando esencialmente igual.  Esto continúa en profundidad y de varias maneras. El texto no es griego, pero mal ilegible América. Comenzó su vida como frases extraídas de las secciones 1.10.32 y 1.10.33 de Cicerón de los extremos del bien y del mal Sin embargo, con el fin de ver cómo toda esta idea errónea de denunciar el placer y el dolor alabando nació, voy a abrir el asunto, y mostrar información acerca de ti o tu sitio explorador de la verdad de él las mismas cosas que debo explicar. No se rechaza, le disgusta o evita el placer mismo, ya que es el placer, sino porque le duele a los que no saben cómo buscar el placer racional. Ni tampoco hay alguien que necesita un profesional dolor Lorem ipsum sit amet, consectetur adipisicing elit, sino porque no trabajo y el dolor de vez en cuando puede caer alguna gran placer. Para tomar un ejemplo trivial, lo que de nosotros se compromete el ejercicio físico trabajoso, excepto para obtener alguna ventaja de ello? Pero, ¿quién tiene derecho a criticar, que deseen disfrutar de un placer que no tiene consecuencias molestas, o uno que evita un dolor que no produce ningún placer resultante? Por otro lado, denunciamos con justos que son más dignos de odio y desmoralizado por los encantos del placer de casos de negocios están cegados por el deseo, no puede prever el dolor y la angustia, que va a abandonar las funciones de la debilidad de la voluntad, lo que se necesita. Estos casos son perfectamente simples y fáciles de distinguir. Se trata de su propio tiempo, con una opción para elegir mujer soltera y cuando nada impide que nos es menos de lo que es más que puede fallar en su deber, todo placer ha de ser acogido y evitar todos los dolores. Sin embargo, en ciertas circunstancias y las necesidades de servicio o de las cosas que con frecuencia ocurre que los placeres tienen que ser repudiado y aceptado molestias. En este es un placer que tiene, o el rechazo de algunos otros placeres mayores, o que sufre dolores de evitar peores dolores.}

  def self.text(locale = 'LA')
    case locale.upcase
    when 'LA'
      LA
    when 'ES'
      ES
    else
      LA
    end
  end
end

